// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChrpZtjnaMxnucSgFenqLJza5eRMWVGa4',
    appId: '1:262944945271:web:8e4e7643e18b78bbdc4272',
    messagingSenderId: '262944945271',
    projectId: 'crud2-dde7a',
    authDomain: 'crud2-dde7a.firebaseapp.com',
    storageBucket: 'crud2-dde7a.appspot.com',
    measurementId: 'G-9CY364YNQW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOtaSt9EJ9dN5Oc5bA3IT15YxsiAMO8M8',
    appId: '1:262944945271:ios:ef353a90493cfd21dc4272',
    messagingSenderId: '262944945271',
    projectId: 'crud2-dde7a',
    storageBucket: 'crud2-dde7a.appspot.com',
    iosBundleId: 'com.example.crud2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOtaSt9EJ9dN5Oc5bA3IT15YxsiAMO8M8',
    appId: '1:262944945271:ios:ef353a90493cfd21dc4272',
    messagingSenderId: '262944945271',
    projectId: 'crud2-dde7a',
    storageBucket: 'crud2-dde7a.appspot.com',
    iosBundleId: 'com.example.crud2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChrpZtjnaMxnucSgFenqLJza5eRMWVGa4',
    appId: '1:262944945271:web:f30635850539b493dc4272',
    messagingSenderId: '262944945271',
    projectId: 'crud2-dde7a',
    authDomain: 'crud2-dde7a.firebaseapp.com',
    storageBucket: 'crud2-dde7a.appspot.com',
    measurementId: 'G-TP42H9F8TJ',
  );
}
